module.exports = {
  PORT: 3000,
  BOOKS: ['1984',
    'Earth Abides',
    'The Martian Chronicles',
    'The Puppet Masters',
    'The Day of the Triffids',
    'Limbo',
    'The Demolished Man',
    'Fahrenheit 451',
    'Childhood\'s End',
    'The Paradox Men',
    'Bring the Jubilee',
    'The Space Merchants',
    'Ring Around the Sun',
    'More Than Human',
    'Mission of Gravity',
    'A Mirror for Observers',
    'The End of Eternity',
    'The Long Tomorrow',
    'The Inheritors',
    'The Stars My Destination',
    'The Death of Grass',
    'The City and the Stars',
    'The Door into Summer',
    'The Midwich Cuckoos',
    'Non-Stop'
  ],
  DB_FILE: 'db.json'
}
